const videoOptions = [
  {
    width: -1,
    height: 240,
    avgBitRate: '150k',
    minBitRate: '75k',
    maxBitRate: '218k',
    tileColumns: '0',
    g: '240',
    threads: '2',
    quality: 'good',
    crf: '37',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    speed: '1',
  },
  {
    width: -1,
    height: 360,
    avgBitRate: '276k',
    minBitRate: '138k',
    maxBitRate: '400k',
    tileColumns: '1',
    g: '240',
    threads: '4',
    quality: 'good',
    crf: '36',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    speed: '4',
  },
  {
    width: -1,
    height: 480,
    avgBitRate: '750k',
    minBitRate: '375k',
    maxBitRate: '1088k',
    tileColumns: '1',
    g: '240',
    threads: '4',
    quality: 'good',
    crf: '33',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    speed: '4',
  },
  {
    width: -1,
    height: 720,
    avgBitRate: '1024k',
    minBitRate: '512k',
    maxBitRate: '1485k',
    tileColumns: '2',
    g: '240',
    threads: '8',
    quality: 'good',
    crf: '32',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    speed: '4',
  },
  {
    width: -1,
    height: 1080,
    avgBitRate: '3000k',
    minBitRate: '1500k',
    maxBitRate: '4350k',
    tileColumns: '2',
    g: '240',
    threads: '8',
    quality: 'good',
    crf: '31',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    speed: '4',
  },
] as const;

export default videoOptions;
